function goChange(tgasd){
	{
	var sinarfmfad = "<object id=\"radioFadzOption\" classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n  <param name=\"movie\" value=\"http://www.sinar.fm/images/Capsule/sinar.swf\">\n  <param name=\"quality\" value=\"high\">\n  <param name=\"wmode\" value=\"transparent\">\n  <param name=\"swfversion\" value=\"9.0.45.0\">\n  <!\-- This param tag prompts users with Flash Player 6.0 r65 and higher to download the latest version of Flash Player. Delete it if you don’t want users to see the prompt. -\->\n  <param name=\"expressinstall\" value=\"http://www.sinar.fm/images/Capsule/expressInstall.swf\">\n  <!-- Next object tag is for non-IE browsers. So hide it from IE using IECC. -\->\n\n  <object type=\"application/x-shockwave-flash\" data=\"http://www.sinar.fm/images/Capsule/sinar.swf\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n    <param name=\"quality\" value=\"high\">\n    <param name=\"wmode\" value=\"transparent\">\n    <param name=\"swfversion\" value=\"9.0.45.0\">\n    <param name=\"expressinstall\" value=\"http://www.sinar.fm/images/Capsule/expressInstall.swf\">\n    <!-- The browser displays the following alternative content for users with Flash Player 6.0 and older. -\->\n    <div>\n      <h4>Content on this page requires a newer version of Adobe Flash Player.</h4>\n      <p><a href=\"http://www.adobe.com/go/getflashplayer\"><img src=\"http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif\" alt=\"Get Adobe Flash player\"></a></p>\n    </div>\n    \n  </object>\n  \n</object>\n </div>";
	var erafmfad = "<object id=\"radioFadzOption\" classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n  <param name=\"movie\" value=\"http://www.era.fm/images/Capsule/era.swf\">\n  <param name=\"quality\" value=\"high\">\n  <param name=\"wmode\" value=\"transparent\">\n  <param name=\"swfversion\" value=\"9.0.45.0\">\n  <!-- This param tag prompts users with Flash Player 6.0 r65 and higher to download the latest version of Flash Player. Delete it if you don’t want users to see the prompt. -\->\n  <param name=\"expressinstall\" value=\"http://www.era.fm/images/Capsule/expressInstall.swf\">\n  <!-- Next object tag is for non-IE browsers. So hide it from IE using IECC. -\->\n  \n  <object type=\"application/x-shockwave-flash\" data=\"http://www.era.fm/images/Capsule/era.swf\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n    \n    <param name=\"quality\" value=\"high\">\n    <param name=\"wmode\" value=\"transparent\">\n    <param name=\"swfversion\" value=\"9.0.45.0\">\n    <param name=\"expressinstall\" value=\"http://www.era.fm/images/Capsule/expressInstall.swf\">\n\n    <!-- The browser displays the following alternative content for users with Flash Player 6.0 and older. -\->\n    <div>\n      <h4>Content on this page requires a newer version of Adobe Flash Player.</h4>\n      <p><a href=\"http://www.adobe.com/go/getflashplayer\"><img src=\"http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif\" alt=\"Get Adobe Flash player\"></a></p>\n    </div>\n\n  </object>\n\n</object>\n </div>";
	var hitzfmfad = "<object id=\"radioFadzOption\" classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n  <param name=\"movie\" value=\"http://www.hitz.fm/images/Capsule/hitz.swf\">\n  <param name=\"quality\" value=\"high\">\n  <param name=\"wmode\" value=\"transparent\">\n  <param name=\"swfversion\" value=\"9.0.45.0\">\n  <!-- This param tag prompts users with Flash Player 6.0 r65 and higher to download the latest version of Flash Player. Delete it if you don’t want users to see the prompt. -\->\n  <param name=\"expressinstall\" value=\"http://www.hitz.fm/images/Capsule/expressInstall.swf\">\n  <!-- Next object tag is for non-IE browsers. So hide it from IE using IECC. -\->\n  \n  <object type=\"application/x-shockwave-flash\" data=\"http://www.hitz.fm/images/Capsule/hitz.swf\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n    \n    <param name=\"quality\" value=\"high\">\n    <param name=\"wmode\" value=\"transparent\">\n    <param name=\"swfversion\" value=\"9.0.45.0\">\n    <param name=\"expressinstall\" value=\"http://www.hitz.fm/images/Capsule/expressInstall.swf\">\n    <!-- The browser displays the following alternative content for users with Flash Player 6.0 and older. -\->\n    <div>\n      <h4>Content on this page requires a newer version of Adobe Flash Player.</h4>\n      <p><a href=\"http://www.adobe.com/go/getflashplayer\"><img src=\"http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif\" alt=\"Get Adobe Flash player\"></a></p>\n    </div>\n    \n  </object>\n  \n</object>\n </div>";
	var xfmfad = "<object id=\"radioFadzOption\" classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n  <param name=\"movie\" value=\"http://www.xfm.com.my/images/Capsule/xfm.swf\">\n  <param name=\"quality\" value=\"high\">\n  <param name=\"wmode\" value=\"transparent\">\n  <param name=\"swfversion\" value=\"9.0.45.0\">\n  <!-- This param tag prompts users with Flash Player 6.0 r65 and higher to download the latest version of Flash Player. Delete it if you don’t want users to see the prompt. -\->\n  <param name=\"expressinstall\" value=\"http://www.xfm.com.my/images/Capsule/expressInstall.swf\">\n  <!-- Next object tag is for non-IE browsers. So hide it from IE using IECC. -\->\n  \n  <object type=\"application/x-shockwave-flash\" data=\"http://www.xfm.com.my/images/Capsule/xfm.swf\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n    \n    <param name=\"quality\" value=\"high\">\n    <param name=\"wmode\" value=\"transparent\">\n    <param name=\"swfversion\" value=\"9.0.45.0\">\n    <param name=\"expressinstall\" value=\"http://www.xfm.com.my/images/Capsule/expressInstall.swf\">\n    <!-- The browser displays the following alternative content for users with Flash Player 6.0 and older. -\->\n    <div>\n      <h4>Content on this page requires a newer version of Adobe Flash Player.</h4>\n      <p><a href=\"http://www.adobe.com/go/getflashplayer\"><img src=\"http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif\" alt=\"Get Adobe Flash player\"></a></p>\n    </div>\n    \n  </object>\n  \n</object>\n </div>";
	var thrgegarfad = "<object id=\"radioFadzOption\" classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n  <param name=\"movie\" value=\"http://gegar.thr.fm/images/Capsule/gegar.swf\">\n  <param name=\"quality\" value=\"high\">\n  <param name=\"wmode\" value=\"transparent\">\n  <param name=\"swfversion\" value=\"9.0.45.0\">\n  <!-- This param tag prompts users with Flash Player 6.0 r65 and higher to download the latest version of Flash Player. Delete it if you don’t want users to see the prompt. -\->\n  <param name=\"expressinstall\" value=\"http://gegar.thr.fm/images/Capsule/expressInstall.swf\">\n  <!-- Next object tag is for non-IE browsers. So hide it from IE using IECC. -\->\n  \n  <object type=\"application/x-shockwave-flash\" data=\"http://gegar.thr.fm/images/Capsule/gegar.swf\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n    \n    <param name=\"quality\" value=\"high\">\n    <param name=\"wmode\" value=\"transparent\">\n    <param name=\"swfversion\" value=\"9.0.45.0\">\n    <param name=\"expressinstall\" value=\"http://gegar.thr.fm/images/Capsule/expressInstall.swf\">\n    <!-- The browser displays the following alternative content for users with Flash Player 6.0 and older. -\->\n    <div>\n      <h4>Content on this page requires a newer version of Adobe Flash Player.</h4>\n      <p><a href=\"http://www.adobe.com/go/getflashplayer\"><img src=\"http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif\" alt=\"Get Adobe Flash player\"></a></p>\n    </div>\n    \n  </object>\n  \n</object>\n </div>";
	var litefmfad = "<object id=\"radioFadzOption\" classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n  <param name=\"movie\" value=\"http://www.litefm.com.my/images/Capsule/lite.swf\">\n  <param name=\"quality\" value=\"high\">\n  <param name=\"wmode\" value=\"transparent\">\n  <param name=\"swfversion\" value=\"9.0.45.0\">\n  <!-- This param tag prompts users with Flash Player 6.0 r65 and higher to download the latest version of Flash Player. Delete it if you don’t want users to see the prompt. -\->\n  <param name=\"expressinstall\" value=\"http://www.litefm.com.my/images/Capsule/expressInstall.swf\">\n  <!-- Next object tag is for non-IE browsers. So hide it from IE using IECC. -\->\n  \n  <object type=\"application/x-shockwave-flash\" data=\"http://www.litefm.com.my/images/Capsule/lite.swf\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n  \n    <param name=\"quality\" value=\"high\">\n    <param name=\"wmode\" value=\"transparent\">\n    <param name=\"swfversion\" value=\"9.0.45.0\">\n    <param name=\"expressinstall\" value=\"http://www.litefm.com.my/images/Capsule/expressInstall.swf\">\n    <!-- The browser displays the following alternative content for users with Flash Player 6.0 and older. -\->\n    <div>\n      <h4>Content on this page requires a newer version of Adobe Flash Player.</h4>\n      <p><a href=\"http://www.adobe.com/go/getflashplayer\"><img src=\"http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif\" alt=\"Get Adobe Flash player\"></a></p>\n    </div>\n   \n  </object>\n  \n</object>";
	var myfmfad = "<object id=\"radioFadzOption\" classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n  <param name=\"movie\" value=\"http://www.my.com.my/images/Capsule/myfm.swf\">\n  <param name=\"quality\" value=\"high\">\n  <param name=\"wmode\" value=\"transparent\">\n  <param name=\"swfversion\" value=\"9.0.45.0\">\n  <!-- This param tag prompts users with Flash Player 6.0 r65 and higher to download the latest version of Flash Player. Delete it if you don’t want users to see the prompt. -\->\n  <param name=\"expressinstall\" value=\"http://www.my.com.my/images/Capsule/expressInstall.swf\">\n  <!-- Next object tag is for non-IE browsers. So hide it from IE using IECC. -\->\n  \n  <object type=\"application/x-shockwave-flash\" data=\"http://www.my.com.my/images/Capsule/myfm.swf\" width=\""+embedWidthFadz+"\" height=\""+embedHeightFadz+"\">\n    \n    <param name=\"quality\" value=\"high\">\n    <param name=\"wmode\" value=\"transparent\">\n    <param name=\"swfversion\" value=\"9.0.45.0\">\n    <param name=\"expressinstall\" value=\"http://www.my.com.my/images/Capsule/expressInstall.swf\">\n    <!-- The browser displays the following alternative content for users with Flash Player 6.0 and older. -\->\n    <div>\n      <h4>Content on this page requires a newer version of Adobe Flash Player.</h4>\n      <p><a href=\"http://www.adobe.com/go/getflashplayer\"><img src=\"http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif\" alt=\"Get Adobe Flash player\"></a></p>\n    </div>\n    \n  </object>\n  \n</object>";
	var hotfmfad = "<embed type=\"application/x-shockwave-flash\" src=\"http://player.streamtheworld.com/_players/stw/v2/GenericLiveAdServer.swf?stamp=1319228472\" width=\""+(embedWidthFadz)+"\" height=\""+(embedHeightFadz)+"\" style=\"undefined\" id=\"radioFadzOption\" name=\"live_player\" bgcolor=\"#666666\" quality=\"high\" wmode=\"transparent\" menu=\"false\" swliveconnect=\"true\" allowscriptaccess=\"always\" allowfullscreen=\"true\" flashvars=\"livePlayerSWF=http://player.streamtheworld.com/_core/assets/swf/liveplayer.swf?stamp=1221763875&amp;baseurl=http://player.streamtheworld.com/_core/&amp;userlevel=0&amp;lang=en&amp;callsign=HOTFM&amp;skintemplate=stw_dark&amp;streamid=11049&amp;showeq=1&amp;shownowplaying=1&amp;showcallsign=1&amp;manualTimeout=0&amp;tryhd=1&amp;adstype=NOADS&amp;clientname=&amp;zoneid=0&amp;tagurl=&amp;targetspot_stationid=&amp;tl_siteCode=&amp;tl_siteCallLetter=&amp;helpurl=&amp;hd_only=1\">";
	var gangsterfm = "<embed type=\"application/x-shockwave-flash\" src=\"http://gengsterfm.tengkorak.info/radio.swf\" width=\""+(embedWidthFadz)+"\" height=\""+(embedHeightFadz)+"\" id=\"radioFadzOption\" name=\"radio\" allowscriptaccess=\"always\" bgcolor=\"#274962\" quality=\"high\" scale=\"noscale\" flashvars=\"swfcolor=274962&amp;swfwidth="+(embedWidthFadz)+"&amp;swfradiochannel=GengSterFM - blASah JeR !!!!!!&amp;swfstreamurl=http://72.20.10.61:8000&amp;swfpause=0\">";
	var vradioChooser = tgasd.options[tgasd.selectedIndex].value;
	var vradioPlace = document.getElementById("radioPlace");
	}
	if(vradioChooser=="Sinar.fm" && radiosinar==true){
		vradioPlace.innerHTML = sinarfmfad;
	}
	else if(vradioChooser=="Era.fm" && radioera==true){
		vradioPlace.innerHTML = erafmfad;
	}
	else if(vradioChooser=="Hitz.fm" && radiohitz==true){
		vradioPlace.innerHTML = hitzfmfad;
	}
	else if(vradioChooser=="X.fm" && radiox==true){
		vradioPlace.innerHTML = xfmfad;
	}
	else if(vradioChooser=="ThrGegar" && radiothrgegar==true){
		vradioPlace.innerHTML = thrgegarfad;
	}
	else if(vradioChooser=="lite.fm" && radiolite==true){
		vradioPlace.innerHTML = litefmfad;
	}
	else if(vradioChooser=="My.fm" && radiomy==true){
		vradioPlace.innerHTML = myfmfad;
	}
	else if(vradioChooser=="Hot.fm" && radiohot==true){
		vradioPlace.innerHTML = hotfmfad;
	}
	else if(vradioChooser=="Gangster.fm" && radiogangster==true){
		vradioPlace.innerHTML = gangsterfm;
	}
	else{
		vradioPlace.innerHTML = "please dont change the option";
	}
}
function treeStartChange(){
	var niceTableRadioChooser = document.getElementById("chooserradioid");
	niceTableRadioChooser.style.width = (embedWidthFadz + 10) + 'px';
	var niceTableRadioChooser = document.getElementById("startPictureRadios");
	niceTableRadioChooser.style.height = (embedHeightFadz) + 'px';
}